{
	"english": {
		"languagename": "English",
		"languagetranslate": "In English",
		"languagecode": "en",
		"english": "English",
		"finnish": "Suomi",
		"russian": "Русский",
		"add": "Add",
		"id": "ID",
		"name": "Name",
		"email": "Email",
		"phone": "Phone",
		"birthdate": "Date of Birth",
		"country": "Country",
		"gender": "Gender",
		"date": "Date",
		"lastlogin": "Last login",
		"lastip": "Last ip",
		"admin": "Administrator",
		"details": "Click here to view details",
		"delete": "Delete",
		"edit": "Edit",
		"featured": "(featured)",
		"hidden": "(hidden)",
		"address": "Address",
		"description": "Description",
		"save": "Save",
		"donotchange": "Do not change, unless necessary!",
		"required": "(required)",
		"field" : "field",
		"format": "Input format",
		"searchby": "Search by",
		"signup": "Signup",
		"login": "Login",
		"logout": "Logout",
		"welcome": "Welcome",
		"welcomeback": "Welcome back",
		"home": "Front page",
		"about": "About us",
		"search": "Search",
		"searchtext": "Search terms...",
		"readmore": "Read more",
		"backtotop": "Go back to top",
		"privacy": "Privacy Policy",
		"terms": "Terms of Service",
		"results": "Results",
		"users": "Users",
		"categories": "Categories",
		"serverlog": "Server log",
		"editprofile": "Edit profile",
		"editingprofile": "Editing user profile",
		"male": "Male",
		"female": "Female",
		"password": "Password",
		"repeatpassword": "Repeat password",
		"apply": "Apply",
		"error": "Error",
		"success": "Success",
		"denied": "Access denied",
		"missing": "Not found",
		"accept": "Accept",
		"fullname": "Firstname Lastname",
		"register": "Register",
		"other": "Other",
		"forgotpass": "Password reset",
		"submit": "Submit",
		"alreadyexists": "already exists",
		"edited": "edited",
		"added": "added",
		"removed": "removed",
		"undefined": "is not defined",
		"empty": "(empty)",
		"incorrect": "Incorrect",
		"username": "Username",
		"password": "Password",
		"loginsuccess": "Login successfull",
		"not": "not",
		"user": "User",
		"needlogin": "You have to login first!",
		"invalid": "(invalid)",
		"passwordtooweak": "Password is too weak",
		"passwordtooshort": "Password is too short",
		"nextpage": "Next page",
		"prevpage": "Previous page",
		"total": "Total",
		"showing": "Showing results",
		"sortmethod": "Sort method",
		"created:desc": "Newest",
		"created:asc": "Oldest",
		"_score:desc": "Relevance",
		"default": "(default)",
		"createdate": "Created",
		"registered": "registered",
		"update": "Update",
		"today": "Today",
		"sent": "sent",
		"select": "Select",
		"captcha": "Captcha",
		"received": "received",
		"pleasewait": "Please wait...",
		"addedby": "Added by",
		"reset": "Reset",
		"sensitive": "Sensitive information",
		"basicinfo": "Basic information",
		"perpage": "per page",
		"upload": "Upload",
		"uploads": "Uploaded files",
		"uploaded": "uploaded",
		"document": "Document",
		"documents": "Documents",
		"notification": "Notifications",
		"content": "Content",
		"domain": "domain",
		"notallowed": "not allowed",
		"unverified": "Unverified",
		"unverifiedtext": "Unverified email address, functionality restricted!",
		"verified": "Verified",
		"verifiedtext": "Email address verified. Account activated!",
		"verify": "Verify email address and activate account.",
		"reverify": "Re-send verification email.",
		"verification": "verification and account activation",
		"close": "Close",
		"role": "role",
		"back": "Back",
		"files": "Files",
		"feedbackpage": "Feedback target page",
		"feedbacktext": "Write your feedback here...",
		"optional": "Optional field",
		"feedback": "Feedback",
		"passwordmustmatch": "Passwords must match",
		"updated": "Updated",
		"already": "is already",
		"needverify": "(Only verified users can see this information)",
		"logininfo": "Login information",
		"saved": "saved",
		"public": "(public)",
		"userinfo": "User information",
		"expired": "(expired)",
		"textinput": "Freeform text input",
		"new": "New",
		"unread": "unread",
		"customcss": "Custom CSS",
		"editcss": "Edit CSS",
		"website": "Website",
		"moments": "Moments",
		"seconds": "second(s)",
		"minutes": "minutes(s)",
		"hours": "hours(s)",
		"days": "days(s)",
		"months": "months(s)",
		"years": "years(s)",
		"ago": "ago",
		"awarded": "Awarded",
		"send": "Send",
		"recovery" : "Recovery",
		"visitor": "(visitor)",
		"unknown": "(unknown)"
	},
	"finnish": {
		"languagename": "Suomi",
		"languagetranslate": "Suomeksi",
		"languagecode": "fi",
		"english": "English",
		"finnish": "Suomi",
		"russian": "Русский",
		"add": "Lisää",
		"id": "ID",
		"name": "Nimi",
		"email": "Sähköposti",
		"phone": "Puhelin",
		"birthdate": "Syntymäpäivä",
		"country": "Maa",
		"gender": "Sukupuoli",
		"date": "Päivämäärä",
		"lastlogin": "Viimeisin kirjautuminen",
		"lastip": "Viimeisin IP",
		"admin": "Järjestelmänvalvoja",
		"details": "Lisätiedot",
		"delete": "Poista",
		"edit": "Muokkaa",
		"featured": "(featured)",
		"hidden": "(piilotettu)",
		"address": "Osoite",
		"description": "Kuvaus",
		"save": "Tallenna",
		"donotchange": "Älä muuta, jos ei ole pakko!",
		"required": "(vaadittu)",
		"field" : "kenttä",
		"format": "Syötteen formaatti",
		"searchby": "Hakuperuste",
		"signup": "Rekisteröidy",
		"login": "Kirjaudu sisään",
		"logout": "Kirjaudu ulos",
		"welcome": "Tervetuloa",
		"welcomeback": "Tervetuloa takaisin",
		"home": "Etusivu",
		"about": "Tietoa",
		"search": "Haku",
		"searchtext": "Hakutermit...",
		"readmore": "Lue lisää",
		"backtotop": "Takaisin ylös",
		"privacy": "Yksityisyys",
		"terms": "Käyttöehdot",
		"results": "Tulokset",
		"users": "Käyttäjät",
		"serverlog": "Palvelimen loki",
		"editprofile": "Muokkaa profiilia",
		"editingprofile": "Muokataan profiilia",
		"male": "Mies",
		"female": "Nainen",
		"password": "Salasana",
		"repeatpassword": "Toista salasana",
		"apply": "Tallenna",
		"error": "Virhe",
		"success": "Onnistui",
		"denied": "Pääsy estetty",
		"missing": "Ei löydy",
		"accept": "Hyväksy",
		"fullname": "Etunimi Sukunimi",
		"register": "Rekisteröidy",
		"other": "Muu",
		"forgotpass": "Salasanan palautus",
		"submit": "Lähetä",
		"alreadyexists": "on jo olemassa",
		"edited": "muokattu",
		"added": "lisätty",
		"removed": "poistettu",
		"undefined": "ei ole määritelty",
		"empty": "(tyhjä)",
		"incorrect": "Virheellinen",
		"username": "Username",
		"password": "Password",
		"loginsuccess": "Onnistunut kirjautuminen",
		"not": "ei",
		"user": "Käyttäjä",
		"needlogin": "Kirjaudu ensin sisään!",
		"invalid": "(virheellinen)",
		"tooweak": "on liian helppo",
		"tooshort": "on liian lyhyt",
		"nextpage": "Seuraava sivu",
		"prevpage": "Edellinen sivu",
		"total": "Kaikkiaan",
		"showing": "Näytetään",
		"sortmethod": "Järjestelyperusta",
		"created:desc": "Uusimmat",
		"created:asc": "Vanhimmat",
		"_score:desc": "Osuvuus",
		"default": "(vakio)",
		"createdate": "Luomispäivä",
		"registered": "rekisteröity",
		"update": "Päivitä",
		"today": "Tänään",
		"sent": "lähetetty",
		"select": "Valitse",
		"captcha": "Captcha",
		"received": "vastaanotettu",
		"pleasewait": "Odota hetki...",
		"addedby": "Lisääjä",
		"reset": "Nollaa",
		"sensitive": "Arkaluonteiset tiedot",
		"basicinfo": "Perustiedot",
		"perpage": "per sivu",
		"upload": "Lataa",
		"uploads": "Ladatut tiedostot",
		"uploaded": "ladattu",
		"document": "Dokumentti",
		"documents": "Dokumentit",
		"notification": "Muistutukset",
		"content": "Sisältö",
		"domain": "domain",
		"notallowed": "ei ole sallittu",
		"unverified": "Vahvistamaton",
		"unverifiedtext": "Vahvistamaton sähköpostiosoite, toiminnot rajattuja!",
		"verified": "Vahvistettu",
		"verifiedtext": "Sähköpostiosoite vahvistettu. Käyttäjä aktivoitu!",
		"verify": "Vahvista sähköpostiosoite ja aktivoi käyttäjä.",
		"reverify": "Lähetä vahvistus sähköposti uudelleen.",
		"verification": "vahvistus ja käyttäjän aktivointi",
		"close": "Sulje",
		"role": "rooli",
		"back": "Takaisin",
		"files": "Tiedostot",
		"optional": "Vaihtoehtoinen kenttä",
		"feedback": "Palaute",
		"passwordmustmatch": "Salasanojen on täsmättävä",
		"updated": "Päivitetty",
		"already": "on jo",
		"needverify": "(Vain vahvistetut käyttäjät voivat nähdä nämä tiedot)",
		"logininfo": "Kirjautumistiedot",
		"saved": "tallennettu",
		"public": "(julkinen)",
		"userinfo": "Käyttäjätiedot",
		"expired": "(vanhentunut)",
		"textinput": "Vapaamuotoinen syötekenttä",
		"new": "Uusi",
		"unread": "lukematon",
		"customcss": "Custom CSS",
		"editcss": "Edit CSS",
		"website": "Sivusto",
		"moments": "Moments",
		"seconds": "second(s)",
		"minutes": "minutes(s)",
		"hours": "hours(s)",
		"days": "days(s)",
		"months": "months(s)",
		"years": "years(s)",
		"ago": "ago",
		"completed": "Suoritettu",
		"incomplete": "Keskeneräinen",
		"awarded": "Myönnetty",
		"send": "Lähetä",
		"recovery" : "Palautus",
		"visitor": "(kävijä)",
		"unknown": "(tuntematon)"
	}
}